version: '3.2'
services:
    nginx:
        image: rawsanj/nginx-lb
        ports:
            - "80:80"
        depends_on:
            - spring-chat-1
            - spring-chat-2
            - spring-chat-3
    redis:
        image: bitnami/redis:4.0.11-r6
        environment:
            - REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "6379:6379"
        volumes:
            - 'redis_data:/bitnami'
    spring-chat-1:
        image: rawsanj/spring-redis-websocket:2.0.0-webflux
        environment:
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
    spring-chat-2:
        image: rawsanj/spring-redis-websocket:2.0.0-webflux
        environment:
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
    spring-chat-3:
        image: rawsanj/spring-redis-websocket:2.0.0-webflux
        environment:
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
volumes:
    redis_data:
        driver: local
