apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-redis-websocket-deployment
    labels:
        app: spring-redis-websocket
spec:
    replicas: 4
    selector:
        matchLabels:
            app: spring-redis-websocket
    template:
        metadata:
            labels:
                app: spring-redis-websocket
        spec:
            containers:
                -   name: spring-redis-websocket
                    image: rawsanj/spring-redis-websocket:2.0.0-webflux
                    resources:
                        limits:
                            memory: "512Mi"
                            cpu: "0.5"
                        requests:
                            memory: "512Mi"
                            cpu: "0.5"
                    ports:
                        -   containerPort: 8080
                    envFrom:
                        -   configMapRef:
                                name: spring-redis-websocket-config
